log:
  level: info
  # file: "/logs/mosdns.log"

# 用于普罗米修斯监控
api:
  http: "0.0.0.0:8338" # api 监听地址

plugins:
  # 只保留转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: "$REMOTE_DNS_SERVER_1"
        # - addr: "$REMOTE_DNS_SERVER_2"
  - tag: ttl_5m
    type: ttl
    args:
      minimal_ttl: 300
      maximum_ttl: 86400
  # 数据统计
  - tag: metrics_collector
    type: metrics_collector

  # 主要运行逻辑：只转发到 forward_remote
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 统计数据，用于Prometheus
        - metrics_collector
        - forward_remote
        - _return
        - ttl_5m

servers:
  - exec: main_sequence
    timeout: 6
    listeners:
      - protocol: udp
        addr: "0.0.0.0:53"
      - protocol: tcp
        addr: "0.0.0.0:53"
      - protocol: http
        addr: "127.0.0.1:9053"
        url_path: "/dns-query"
        get_user_ip_from_header: "X-Forwarded-For"
      #- protocol: tls             
      #  addr: "0.0.0.0:853"
      #  cert: "/etc/mosdns/yourdomain.cert"  # TLS 所需证书文件。
      #  key: "/etc/mosdns/yourdomain.key"    # TLS 所需密钥文件。
